// backend/src/agents/createAgent.ts

import { StreamChat } from "stream-chat";
import { apiKey, serverClient } from "../serverClient";
import { OpenAIAgent } from "./openai/OpenAIAgent";
import { AgentPlatform, AIAgent } from "./types";
import { GroqAgent } from "./groq/GroqAgent";


export const createAgent = async (
  user_id: string,
  platform: AgentPlatform,
  channel_type: string,
  channel_id: string
): Promise<AIAgent> => {
  // Token for the bot user, generated by the server-side client
  const token = serverClient.createToken(user_id);
  // This is the *client* for the AI bot user that connects to Stream
  const chatClient = new StreamChat(apiKey, undefined, {
    allowServerSideConnect: true,
  });

  await chatClient.connectUser({ id: user_id }, token);
  const channel = chatClient.channel(channel_type, channel_id);
  await channel.watch();

  switch (platform) {
    case AgentPlatform.GROQ:
      return new GroqAgent(chatClient, channel);

    case AgentPlatform.WRITING_ASSISTANT:
    case AgentPlatform.OPENAI:
      throw new Error("OpenAI agent is disabled. Use GROQ instead.");

    default:
      throw new Error(`Unsupported agent platform: ${platform}`);
  }
};